export const chek = [
  { produkt: "CocaCola", skiko: 1, price: 40 },
  { produkt: "Milk", skiko: 1, price: 30 },
  { produkt: "Eggs", skiko: 10, price: 80 },
  { produkt: "Avocado", skiko: 3, price: 60 },
  { produkt: "Salo", skiko: 1, price: 100 },
  { produkt: "Potato", skiko: 10, price: 50 },
  { produkt: "Meet", skiko: 2, price: 100 },
  { produkt: "OliveOil", skiko: 1, price: 100 },
  { produkt: "Chiken", skiko: 1, price: 100 },
  { produkt: "Candys", skiko: 2, price: 50 },
  { produkt: "Salat", skiko: 1, price: 80 },
  { produkt: "Orange", skiko: 1, price: 80 },
  { produkt: "Pizza", skiko: 2, price: 120 },
  { produkt: "Wiskas", skiko: 1, price: 200 },
  { produkt: "Fish", skiko: 1, price: 200 },
  { produkt: "Lemon", skiko: 3, price: 80 },
  { produkt: "Kiwi", skiko: 3, price: 80 },
  { produkt: "Pripravka", skiko: 1, price: 40 },
  { produkt: "TyaletnaBumaga", skiko: 20, price: 20 },
];