export const data = [
  { produkt: "CocaCola", skiko: 1, status: true },
  { produkt: "Milk", skiko: 1, status: false },
  { produkt: "Eggs", skiko: 10, status: true },
  { produkt: "Avocado", skiko: 3, status: true },
  { produkt: "Salo", skiko: 1, status: false },
  { produkt: "Potato", skiko: 10, status: true },
  { produkt: "Meet", skiko: 2, status: false },
  { produkt: "OliveOil", skiko: 1, status: true },
  { produkt: "Chiken", skiko: 1, status: false },
  { produkt: "Candys", skiko: 2, status: true },
  { produkt: "Salat", skiko: 1, status: false },
  { produkt: "Orange", skiko: 1, status: true },
  { produkt: "Pizza", skiko: 2, status: true },
  { produkt: "Wiskas", skiko: 1, status: false },
  { produkt: "Fish", skiko: 1, status: true },
  { produkt: "Lemon", skiko: 3, status: false },
  { produkt: "Kiwi", skiko: 3, status:true  },
  { produkt: "Pripravka", skiko: 1, status: false },
  { produkt: "TyaletnaBumaga", skiko: 20, status: true },
];